import './globals.css'
import { Inter } from "next/font/google";
import AppProvider from '@/providers/AppProvider';
import MainLayout from '@/components/MainLayout';
// * 사이드바 Provider를 선언하여 모든 페이지에서 동일한 상태를 공유
import  { SidebarProvider } from '@/context/SidebarContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarProvider>
            <AppProvider>
                <MainLayout>
                    {children}
                </MainLayout>
            </AppProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
