import { ChakraProvider } from '@chakra-ui/react';
import { Inter } from "next/font/google";
// import "./globals.css";
import 'semantic-ui-css/semantic.min.css';
import Link from 'next/link';
import { Providers } from './providers';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
            <div className='ui center aligned four column grid'>
                <div className='row '>
                    <div className='column'>
                        <div className='ui segment'>
                        <Link href='/'>홈</Link></div>
                    </div>
                    <div className='column'>
                        <div className='ui segment'>
                        <Link href='/list'>리스트</Link></div>
                    </div>
                    <div className='column'>
                        <div className='ui segment'>
                        <Link href='/products'>상품</Link></div>
                    </div>
                </div>
            </div>
            {children}
        </Providers>
       </body>
    </html>
  );
}
