[build]
  command = "yarn install && yarn build"
  publish = "out"
  environment = { NODE_VERSION = "20.15.0" }
  

[context.production.environment]
  NODE_VERSION = "20.15.0"

[[plugins]]
package = "@netlify/plugin-nextjs"